### ISSUE TITLE
How to authenticate for Azure DevOps hosted git repository?

### ISSUE THREAD

**Issue by Silthus** [DanielHabenicht/AzurePipelines-SemanticRelease#120]
How can I pass an authentication token if the repo is hosted directly in Azure DevOps and not Github?

```text
Starting: freestyle
==============================================================================
Task         : Semantic Release Freestyle
Description  : Task for simplifying Semantic Release (0.0.53)
Version      : 0.0.53
Author       : Daniel Habenicht
Help         : https://github.com/DanielHabenicht/AzurePipelines-SemanticRelease/issues
==============================================================================
/usr/local/bin/npm install --only=prod semantic-release@17 @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/git
+ semantic-release@17.0.7
+ @semantic-release/git@9.0.0
+ @semantic-release/changelog@5.0.1
+ @semantic-release/commit-analyzer@8.0.1
+ @semantic-release/release-notes-generator@9.0.1
added 792 packages from 1021 contributors and audited 13935 packages in 21.378s

16 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
[3:12:50 PM] [semantic-release] › ℹ  Running semantic-release version 17.0.7
[3:12:50 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[3:12:50 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[3:12:50 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[3:12:50 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[3:12:50 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[3:12:50 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[3:12:51 PM] [semantic-release] › ✖  An error occurred while running semantic-release: { Error: Command failed with exit code 128: git ls-remote --heads https://********@dev.azure.com/********/********/_git/tf.shared
fatal: could not read Password for 'https://********@dev.azure.com': terminal prompts disabled
    at makeError (/home/vsts/work/_tasks/freestyle_87a45e6c-a243-455c-861d-37404e26212d/0.0.53/node_modules/semantic-release/node_modules/execa/lib/error.js:58:11)
##[error]Command failed with exit code 128: git ls-remote --heads https://********@dev.azure.com/********/********/_git/tf.shared
fatal: could not read Password for 'https://********@dev.azure.com': terminal prompts disabled
    at handlePromise (/home/vsts/work/_tasks/freestyle_87a45e6c-a243-455c-861d-37404e26212d/0.0.53/node_modules/semantic-release/node_modules/execa/index.js:114:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  shortMessage:
   'Command failed with exit code 128: git ls-remote --heads https://********@dev.azure.com/********/********/_git/tf.shared',
  command:
   'git ls-remote --heads https://********@dev.azure.com/********/********/_git/tf.shared',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr:
   'fatal: could not read Password for \'https://********@dev.azure.com\': terminal prompts disabled',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false }
Finishing: freestyle

```

**Comment by DanielHabenicht** [comment]
That's not an issue with semantic-release, nor with this extension. But as I investigated please follow either this guide: 
https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml

or these steps: 
1. Set the your "Build Service" Account (as described in the article) to the following policies:
![image](https://user-images.githubusercontent.com/13590797/80152852-baa5df00-85bc-11ea-870c-2df8633daad9.png)

2. Add this to your repo checkout task:
```yaml
- checkout: self
  persistCredentials: true
```

If that doesn't solve your problem please write back.
