### ISSUE TITLE
 fatal: could not read Password ....

### ISSUE THREAD

**Issue by hmendezm** [DanielHabenicht/AzurePipelines-SemanticRelease#192]
Hi Guys,

This extension has worked very nice but since Yesterday it is not working anymore. I did not change the pipeline or azure. Do you have any idea why? I created a new git service connection but it is failing.
```

2021-07-14T14:15:06.9125187Z [2:15:06 PM] [semantic-release] » ×  An error occurred while running semantic-release: { Error: Command failed with exit code 128: git ls-remote --heads https://[secure]@dev.azure.com/...
2021-07-14T14:15:06.9126560Z fatal: Cannot prompt because user interactivity has been disabled.
2021-07-14T14:15:06.9136290Z fatal: Cannot prompt because user interactivity has been disabled.
2021-07-14T14:15:06.9137505Z fatal: could not read Password for 'https://[secure]@dev.azure.com/.....': terminal prompts disabled
2021-07-14T14:15:06.9138842Z     at makeError (D:\a\_tasks\freestyle_87a45e6c-a243-455c-861d-37404e26212d\0.0.53\node_modules\semantic-release\node_modules\execa\lib\error.js:60:11)
2021-07-14T14:15:06.9139950Z     at handlePromise (D:\a\_tasks\freestyle_87a45e6c-a243-455c-861d-37404e26212d\0.0.53\node_modules\semantic-release\node_modules\execa\index.js:118:26)
2021-07-14T14:15:06.9142212Z     at process._tickCallback (internal/process/next_tick.js:68:7)
2021-07-14T14:15:06.9142651Z   shortMessage:
2021-07-14T14:15:06.9143255Z    'Command failed with exit code 128: git ls-remote --heads https://[secure]@dev.azure.com/...',
2021-07-14T14:15:06.9143795Z   command:
2021-07-14T14:15:06.9144334Z    'git ls-remote --heads https://[secure]@dev.azure.com/...',
2021-07-14T14:15:06.9145435Z   escapedCommand:
2021-07-14T14:15:06.9155848Z    'git ls-remote --heads "https://[secure]@dev.azure.com/...."',
2021-07-14T14:15:06.9156923Z   exitCode: 128,
2021-07-14T14:15:06.9160643Z   signal: undefined,
2021-07-14T14:15:06.9161314Z   signalDescription: undefined,
2021-07-14T14:15:06.9161991Z   stdout: '',
2021-07-14T14:15:06.9162466Z   stderr:
2021-07-14T14:15:06.9166796Z    'fatal: Cannot prompt because user interactivity has been disabled.\nfatal: Cannot prompt because user interactivity has been disabled.\nfatal: could not read Password for \'https://[secure]@dev.azure.com/...': terminal prompts disabled',
2021-07-14T14:15:06.9168297Z   failed: true,
2021-07-14T14:15:06.9168890Z   timedOut: false,
2021-07-14T14:15:06.9169463Z   isCanceled: false,
2021-07-14T14:15:06.9170072Z   killed: false }
```

**Comment by DanielHabenicht** [comment]
I will have a look tomorrow evening

**Comment by hmendezm** [comment]
Thanks, Daniel!
